Gem::Specification.new do |s|
  s.specification_version = 2 if s.respond_to? :specification_version=
  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.rubygems_version = '1.3.5'

  ## Leave these as is they will be modified for you by the rake gemspec task.
  ## If your rubyforge_project name is different, then edit it and comment out
  ## the sub! line in the Rakefile
  s.name              = 'brightbox-fog'
  s.version           = '0.3.16'
  s.date              = '2010-11-05'
  s.rubyforge_project = 'brightbox-fog'

  ## Make sure your summary is short. The description may be as long
  ## as you like.
  s.summary     = "brings clouds to you"
  s.description = "The Ruby cloud computing library (with Brightbox cloud support)"

  ## List the primary authors. If there are a bunch of authors, it's probably
  ## better to set the email to an email list or something. If you don't have
  ## a custom homepage, consider using your GitHub URL or the like.
  s.authors  = ["Brightbox Systems Limited", "geemus (Wesley Beary)"]
  s.email    = 'geemus@gmail.com'
  s.homepage = 'http://github.com/geemus/fog'

  ## This gets added to the $LOAD_PATH so that 'lib/NAME.rb' can be required as
  ## require 'NAME.rb' or'/lib/NAME/file.rb' can be as require 'NAME/file.rb'
  s.require_paths = %w[lib]

  ## This sections is only necessary if you have C extensions.
  # s.require_paths << 'ext'
  # s.extensions = %w[ext/extconf.rb]

  ## If your gem includes any executables, list them here.
  s.executables = ["bbfog"]
  s.default_executable = 'bbfog'

  ## Specify any RDoc options here. You'll want to add your README and
  ## LICENSE files to the extra_rdoc_files list.
  s.rdoc_options = ["--charset=UTF-8"]
  s.extra_rdoc_files = %w[README.rdoc]

  ## List your runtime dependencies here. Runtime dependencies are those
  ## that are needed for an end user to actually USE your code.
  s.add_dependency('builder')
  s.add_dependency('excon', '>=0.2.4')
  s.add_dependency('formatador', '>=0.0.15')
  s.add_dependency('json')
  s.add_dependency('mime-types')
  s.add_dependency('net-ssh', '~>2.0.23')
  s.add_dependency('nokogiri', '~>1.4.3.1')
  s.add_dependency('ruby-hmac')

  ## List your development dependencies here. Development dependencies are
  ## those that are only needed during development
  s.add_development_dependency('rake')
  s.add_development_dependency('rspec')
  s.add_development_dependency('shindo', '0.1.7')

  ## Leave this section as-is. It will be automatically generated from the
  ## contents of your Git repository via the gemspec task. DO NOT REMOVE
  ## THE MANIFEST COMMENTS, they are used as delimiters by the task.
  # = MANIFEST =
  s.files = %w[
    Gemfile
    Gemfile.lock
    README.rdoc
    Rakefile
    benchs/fog_vs.rb
    benchs/params.rb
    benchs/parse_vs_push.rb
    bin/bbfog
    brightbox-fog.gemspec
    examples/bluebox_create.rb
    lib/brightbox-fog.rb
    lib/brightbox-fog/aws.rb
    lib/brightbox-fog/aws/bin.rb
    lib/brightbox-fog/aws/cdn.rb
    lib/brightbox-fog/aws/compute.rb
    lib/brightbox-fog/aws/ec2.rb
    lib/brightbox-fog/aws/elb.rb
    lib/brightbox-fog/aws/iam.rb
    lib/brightbox-fog/aws/models/compute/address.rb
    lib/brightbox-fog/aws/models/compute/addresses.rb
    lib/brightbox-fog/aws/models/compute/flavor.rb
    lib/brightbox-fog/aws/models/compute/flavors.rb
    lib/brightbox-fog/aws/models/compute/image.rb
    lib/brightbox-fog/aws/models/compute/images.rb
    lib/brightbox-fog/aws/models/compute/key_pair.rb
    lib/brightbox-fog/aws/models/compute/key_pairs.rb
    lib/brightbox-fog/aws/models/compute/security_group.rb
    lib/brightbox-fog/aws/models/compute/security_groups.rb
    lib/brightbox-fog/aws/models/compute/server.rb
    lib/brightbox-fog/aws/models/compute/servers.rb
    lib/brightbox-fog/aws/models/compute/snapshot.rb
    lib/brightbox-fog/aws/models/compute/snapshots.rb
    lib/brightbox-fog/aws/models/compute/tag.rb
    lib/brightbox-fog/aws/models/compute/tags.rb
    lib/brightbox-fog/aws/models/compute/volume.rb
    lib/brightbox-fog/aws/models/compute/volumes.rb
    lib/brightbox-fog/aws/models/storage/directories.rb
    lib/brightbox-fog/aws/models/storage/directory.rb
    lib/brightbox-fog/aws/models/storage/file.rb
    lib/brightbox-fog/aws/models/storage/files.rb
    lib/brightbox-fog/aws/parsers/cdn/distribution.rb
    lib/brightbox-fog/aws/parsers/cdn/get_distribution_list.rb
    lib/brightbox-fog/aws/parsers/cdn/post_invalidation.rb
    lib/brightbox-fog/aws/parsers/compute/allocate_address.rb
    lib/brightbox-fog/aws/parsers/compute/attach_volume.rb
    lib/brightbox-fog/aws/parsers/compute/basic.rb
    lib/brightbox-fog/aws/parsers/compute/create_image.rb
    lib/brightbox-fog/aws/parsers/compute/create_key_pair.rb
    lib/brightbox-fog/aws/parsers/compute/create_snapshot.rb
    lib/brightbox-fog/aws/parsers/compute/create_volume.rb
    lib/brightbox-fog/aws/parsers/compute/deregister_image.rb
    lib/brightbox-fog/aws/parsers/compute/describe_addresses.rb
    lib/brightbox-fog/aws/parsers/compute/describe_availability_zones.rb
    lib/brightbox-fog/aws/parsers/compute/describe_images.rb
    lib/brightbox-fog/aws/parsers/compute/describe_instances.rb
    lib/brightbox-fog/aws/parsers/compute/describe_key_pairs.rb
    lib/brightbox-fog/aws/parsers/compute/describe_regions.rb
    lib/brightbox-fog/aws/parsers/compute/describe_reserved_instances.rb
    lib/brightbox-fog/aws/parsers/compute/describe_security_groups.rb
    lib/brightbox-fog/aws/parsers/compute/describe_snapshots.rb
    lib/brightbox-fog/aws/parsers/compute/describe_tags.rb
    lib/brightbox-fog/aws/parsers/compute/describe_volumes.rb
    lib/brightbox-fog/aws/parsers/compute/detach_volume.rb
    lib/brightbox-fog/aws/parsers/compute/get_console_output.rb
    lib/brightbox-fog/aws/parsers/compute/import_key_pair.rb
    lib/brightbox-fog/aws/parsers/compute/register_image.rb
    lib/brightbox-fog/aws/parsers/compute/run_instances.rb
    lib/brightbox-fog/aws/parsers/compute/start_stop_instances.rb
    lib/brightbox-fog/aws/parsers/compute/terminate_instances.rb
    lib/brightbox-fog/aws/parsers/elb/create_load_balancer.rb
    lib/brightbox-fog/aws/parsers/elb/delete_load_balancer.rb
    lib/brightbox-fog/aws/parsers/elb/deregister_instances_from_load_balancer.rb
    lib/brightbox-fog/aws/parsers/elb/describe_instance_health.rb
    lib/brightbox-fog/aws/parsers/elb/describe_load_balancers.rb
    lib/brightbox-fog/aws/parsers/elb/disable_availability_zones_for_load_balancer.rb
    lib/brightbox-fog/aws/parsers/elb/enable_availability_zones_for_load_balancer.rb
    lib/brightbox-fog/aws/parsers/elb/register_instances_with_load_balancer.rb
    lib/brightbox-fog/aws/parsers/iam/basic.rb
    lib/brightbox-fog/aws/parsers/iam/create_group.rb
    lib/brightbox-fog/aws/parsers/iam/list_groups.rb
    lib/brightbox-fog/aws/parsers/simpledb/basic.rb
    lib/brightbox-fog/aws/parsers/simpledb/domain_metadata.rb
    lib/brightbox-fog/aws/parsers/simpledb/get_attributes.rb
    lib/brightbox-fog/aws/parsers/simpledb/list_domains.rb
    lib/brightbox-fog/aws/parsers/simpledb/select.rb
    lib/brightbox-fog/aws/parsers/storage/access_control_list.rb
    lib/brightbox-fog/aws/parsers/storage/copy_object.rb
    lib/brightbox-fog/aws/parsers/storage/get_bucket.rb
    lib/brightbox-fog/aws/parsers/storage/get_bucket_location.rb
    lib/brightbox-fog/aws/parsers/storage/get_bucket_logging.rb
    lib/brightbox-fog/aws/parsers/storage/get_bucket_object_versions.rb
    lib/brightbox-fog/aws/parsers/storage/get_bucket_versioning.rb
    lib/brightbox-fog/aws/parsers/storage/get_request_payment.rb
    lib/brightbox-fog/aws/parsers/storage/get_service.rb
    lib/brightbox-fog/aws/requests/cdn/delete_distribution.rb
    lib/brightbox-fog/aws/requests/cdn/get_distribution.rb
    lib/brightbox-fog/aws/requests/cdn/get_distribution_list.rb
    lib/brightbox-fog/aws/requests/cdn/post_distribution.rb
    lib/brightbox-fog/aws/requests/cdn/post_invalidation.rb
    lib/brightbox-fog/aws/requests/compute/allocate_address.rb
    lib/brightbox-fog/aws/requests/compute/associate_address.rb
    lib/brightbox-fog/aws/requests/compute/attach_volume.rb
    lib/brightbox-fog/aws/requests/compute/authorize_security_group_ingress.rb
    lib/brightbox-fog/aws/requests/compute/create_image.rb
    lib/brightbox-fog/aws/requests/compute/create_key_pair.rb
    lib/brightbox-fog/aws/requests/compute/create_security_group.rb
    lib/brightbox-fog/aws/requests/compute/create_snapshot.rb
    lib/brightbox-fog/aws/requests/compute/create_tags.rb
    lib/brightbox-fog/aws/requests/compute/create_volume.rb
    lib/brightbox-fog/aws/requests/compute/delete_key_pair.rb
    lib/brightbox-fog/aws/requests/compute/delete_security_group.rb
    lib/brightbox-fog/aws/requests/compute/delete_snapshot.rb
    lib/brightbox-fog/aws/requests/compute/delete_tags.rb
    lib/brightbox-fog/aws/requests/compute/delete_volume.rb
    lib/brightbox-fog/aws/requests/compute/deregister_image.rb
    lib/brightbox-fog/aws/requests/compute/describe_addresses.rb
    lib/brightbox-fog/aws/requests/compute/describe_availability_zones.rb
    lib/brightbox-fog/aws/requests/compute/describe_images.rb
    lib/brightbox-fog/aws/requests/compute/describe_instances.rb
    lib/brightbox-fog/aws/requests/compute/describe_key_pairs.rb
    lib/brightbox-fog/aws/requests/compute/describe_regions.rb
    lib/brightbox-fog/aws/requests/compute/describe_reserved_instances.rb
    lib/brightbox-fog/aws/requests/compute/describe_security_groups.rb
    lib/brightbox-fog/aws/requests/compute/describe_snapshots.rb
    lib/brightbox-fog/aws/requests/compute/describe_tags.rb
    lib/brightbox-fog/aws/requests/compute/describe_volumes.rb
    lib/brightbox-fog/aws/requests/compute/detach_volume.rb
    lib/brightbox-fog/aws/requests/compute/disassociate_address.rb
    lib/brightbox-fog/aws/requests/compute/get_console_output.rb
    lib/brightbox-fog/aws/requests/compute/import_key_pair.rb
    lib/brightbox-fog/aws/requests/compute/modify_image_attributes.rb
    lib/brightbox-fog/aws/requests/compute/modify_snapshot_attribute.rb
    lib/brightbox-fog/aws/requests/compute/reboot_instances.rb
    lib/brightbox-fog/aws/requests/compute/register_image.rb
    lib/brightbox-fog/aws/requests/compute/release_address.rb
    lib/brightbox-fog/aws/requests/compute/revoke_security_group_ingress.rb
    lib/brightbox-fog/aws/requests/compute/run_instances.rb
    lib/brightbox-fog/aws/requests/compute/start_instances.rb
    lib/brightbox-fog/aws/requests/compute/stop_instances.rb
    lib/brightbox-fog/aws/requests/compute/terminate_instances.rb
    lib/brightbox-fog/aws/requests/elb/create_load_balancer.rb
    lib/brightbox-fog/aws/requests/elb/delete_load_balancer.rb
    lib/brightbox-fog/aws/requests/elb/deregister_instances_from_load_balancer.rb
    lib/brightbox-fog/aws/requests/elb/describe_instance_health.rb
    lib/brightbox-fog/aws/requests/elb/describe_load_balancers.rb
    lib/brightbox-fog/aws/requests/elb/disable_availability_zones_for_load_balancer.rb
    lib/brightbox-fog/aws/requests/elb/enable_availability_zones_for_load_balancer.rb
    lib/brightbox-fog/aws/requests/elb/register_instances_with_load_balancer.rb
    lib/brightbox-fog/aws/requests/iam/create_group.rb
    lib/brightbox-fog/aws/requests/iam/delete_group.rb
    lib/brightbox-fog/aws/requests/iam/list_groups.rb
    lib/brightbox-fog/aws/requests/simpledb/batch_put_attributes.rb
    lib/brightbox-fog/aws/requests/simpledb/create_domain.rb
    lib/brightbox-fog/aws/requests/simpledb/delete_attributes.rb
    lib/brightbox-fog/aws/requests/simpledb/delete_domain.rb
    lib/brightbox-fog/aws/requests/simpledb/domain_metadata.rb
    lib/brightbox-fog/aws/requests/simpledb/get_attributes.rb
    lib/brightbox-fog/aws/requests/simpledb/list_domains.rb
    lib/brightbox-fog/aws/requests/simpledb/put_attributes.rb
    lib/brightbox-fog/aws/requests/simpledb/select.rb
    lib/brightbox-fog/aws/requests/storage/copy_object.rb
    lib/brightbox-fog/aws/requests/storage/delete_bucket.rb
    lib/brightbox-fog/aws/requests/storage/delete_object.rb
    lib/brightbox-fog/aws/requests/storage/get_bucket.rb
    lib/brightbox-fog/aws/requests/storage/get_bucket_acl.rb
    lib/brightbox-fog/aws/requests/storage/get_bucket_location.rb
    lib/brightbox-fog/aws/requests/storage/get_bucket_logging.rb
    lib/brightbox-fog/aws/requests/storage/get_bucket_object_versions.rb
    lib/brightbox-fog/aws/requests/storage/get_bucket_versioning.rb
    lib/brightbox-fog/aws/requests/storage/get_object.rb
    lib/brightbox-fog/aws/requests/storage/get_object_acl.rb
    lib/brightbox-fog/aws/requests/storage/get_object_torrent.rb
    lib/brightbox-fog/aws/requests/storage/get_object_url.rb
    lib/brightbox-fog/aws/requests/storage/get_request_payment.rb
    lib/brightbox-fog/aws/requests/storage/get_service.rb
    lib/brightbox-fog/aws/requests/storage/head_object.rb
    lib/brightbox-fog/aws/requests/storage/post_object_hidden_fields.rb
    lib/brightbox-fog/aws/requests/storage/put_bucket.rb
    lib/brightbox-fog/aws/requests/storage/put_bucket_acl.rb
    lib/brightbox-fog/aws/requests/storage/put_bucket_logging.rb
    lib/brightbox-fog/aws/requests/storage/put_bucket_versioning.rb
    lib/brightbox-fog/aws/requests/storage/put_object.rb
    lib/brightbox-fog/aws/requests/storage/put_object_url.rb
    lib/brightbox-fog/aws/requests/storage/put_request_payment.rb
    lib/brightbox-fog/aws/s3.rb
    lib/brightbox-fog/aws/simpledb.rb
    lib/brightbox-fog/aws/storage.rb
    lib/brightbox-fog/bluebox.rb
    lib/brightbox-fog/bluebox/bin.rb
    lib/brightbox-fog/bluebox/compute.rb
    lib/brightbox-fog/bluebox/models/compute/flavor.rb
    lib/brightbox-fog/bluebox/models/compute/flavors.rb
    lib/brightbox-fog/bluebox/models/compute/image.rb
    lib/brightbox-fog/bluebox/models/compute/images.rb
    lib/brightbox-fog/bluebox/models/compute/server.rb
    lib/brightbox-fog/bluebox/models/compute/servers.rb
    lib/brightbox-fog/bluebox/requests/compute/create_block.rb
    lib/brightbox-fog/bluebox/requests/compute/destroy_block.rb
    lib/brightbox-fog/bluebox/requests/compute/get_block.rb
    lib/brightbox-fog/bluebox/requests/compute/get_blocks.rb
    lib/brightbox-fog/bluebox/requests/compute/get_product.rb
    lib/brightbox-fog/bluebox/requests/compute/get_products.rb
    lib/brightbox-fog/bluebox/requests/compute/get_template.rb
    lib/brightbox-fog/bluebox/requests/compute/get_templates.rb
    lib/brightbox-fog/bluebox/requests/compute/reboot_block.rb
    lib/brightbox-fog/brightbox.rb
    lib/brightbox-fog/brightbox/bin.rb
    lib/brightbox-fog/brightbox/compute.rb
    lib/brightbox-fog/brightbox/models/compute/account.rb
    lib/brightbox-fog/brightbox/models/compute/cloud_ip.rb
    lib/brightbox-fog/brightbox/models/compute/cloud_ips.rb
    lib/brightbox-fog/brightbox/models/compute/flavor.rb
    lib/brightbox-fog/brightbox/models/compute/flavors.rb
    lib/brightbox-fog/brightbox/models/compute/image.rb
    lib/brightbox-fog/brightbox/models/compute/images.rb
    lib/brightbox-fog/brightbox/models/compute/server.rb
    lib/brightbox-fog/brightbox/models/compute/servers.rb
    lib/brightbox-fog/brightbox/models/compute/user.rb
    lib/brightbox-fog/brightbox/models/compute/users.rb
    lib/brightbox-fog/brightbox/models/compute/zone.rb
    lib/brightbox-fog/brightbox/models/compute/zones.rb
    lib/brightbox-fog/brightbox/requests/compute/create_api_client.rb
    lib/brightbox-fog/brightbox/requests/compute/create_cloud_ip.rb
    lib/brightbox-fog/brightbox/requests/compute/create_image.rb
    lib/brightbox-fog/brightbox/requests/compute/create_server.rb
    lib/brightbox-fog/brightbox/requests/compute/destroy_api_client.rb
    lib/brightbox-fog/brightbox/requests/compute/destroy_cloud_ip.rb
    lib/brightbox-fog/brightbox/requests/compute/destroy_image.rb
    lib/brightbox-fog/brightbox/requests/compute/destroy_server.rb
    lib/brightbox-fog/brightbox/requests/compute/get_account.rb
    lib/brightbox-fog/brightbox/requests/compute/get_api_client.rb
    lib/brightbox-fog/brightbox/requests/compute/get_cloud_ip.rb
    lib/brightbox-fog/brightbox/requests/compute/get_image.rb
    lib/brightbox-fog/brightbox/requests/compute/get_interface.rb
    lib/brightbox-fog/brightbox/requests/compute/get_server.rb
    lib/brightbox-fog/brightbox/requests/compute/get_server_type.rb
    lib/brightbox-fog/brightbox/requests/compute/get_user.rb
    lib/brightbox-fog/brightbox/requests/compute/get_zone.rb
    lib/brightbox-fog/brightbox/requests/compute/list_api_clients.rb
    lib/brightbox-fog/brightbox/requests/compute/list_cloud_ips.rb
    lib/brightbox-fog/brightbox/requests/compute/list_images.rb
    lib/brightbox-fog/brightbox/requests/compute/list_server_types.rb
    lib/brightbox-fog/brightbox/requests/compute/list_servers.rb
    lib/brightbox-fog/brightbox/requests/compute/list_users.rb
    lib/brightbox-fog/brightbox/requests/compute/list_zones.rb
    lib/brightbox-fog/brightbox/requests/compute/map_cloud_ip.rb
    lib/brightbox-fog/brightbox/requests/compute/rebuild_server.rb
    lib/brightbox-fog/brightbox/requests/compute/reset_ftp_password_account.rb
    lib/brightbox-fog/brightbox/requests/compute/resize_server.rb
    lib/brightbox-fog/brightbox/requests/compute/restart_server.rb
    lib/brightbox-fog/brightbox/requests/compute/shutdown_server.rb
    lib/brightbox-fog/brightbox/requests/compute/snapshot_server.rb
    lib/brightbox-fog/brightbox/requests/compute/start_server.rb
    lib/brightbox-fog/brightbox/requests/compute/stop_server.rb
    lib/brightbox-fog/brightbox/requests/compute/unmap_cloud_ip.rb
    lib/brightbox-fog/brightbox/requests/compute/update_account.rb
    lib/brightbox-fog/brightbox/requests/compute/update_api_client.rb
    lib/brightbox-fog/brightbox/requests/compute/update_image.rb
    lib/brightbox-fog/brightbox/requests/compute/update_server.rb
    lib/brightbox-fog/brightbox/requests/compute/update_user.rb
    lib/brightbox-fog/core.rb
    lib/brightbox-fog/core/attributes.rb
    lib/brightbox-fog/core/bin.rb
    lib/brightbox-fog/core/collection.rb
    lib/brightbox-fog/core/compute.rb
    lib/brightbox-fog/core/connection.rb
    lib/brightbox-fog/core/credentials.rb
    lib/brightbox-fog/core/deprecation.rb
    lib/brightbox-fog/core/errors.rb
    lib/brightbox-fog/core/hmac.rb
    lib/brightbox-fog/core/model.rb
    lib/brightbox-fog/core/parser.rb
    lib/brightbox-fog/core/provider.rb
    lib/brightbox-fog/core/service.rb
    lib/brightbox-fog/core/ssh.rb
    lib/brightbox-fog/core/storage.rb
    lib/brightbox-fog/go_grid.rb
    lib/brightbox-fog/go_grid/bin.rb
    lib/brightbox-fog/go_grid/compute.rb
    lib/brightbox-fog/go_grid/models/compute/image.rb
    lib/brightbox-fog/go_grid/models/compute/images.rb
    lib/brightbox-fog/go_grid/models/compute/server.rb
    lib/brightbox-fog/go_grid/models/compute/servers.rb
    lib/brightbox-fog/go_grid/requests/compute/common_lookup_list.rb
    lib/brightbox-fog/go_grid/requests/compute/grid_image_get.rb
    lib/brightbox-fog/go_grid/requests/compute/grid_image_list.rb
    lib/brightbox-fog/go_grid/requests/compute/grid_ip_list.rb
    lib/brightbox-fog/go_grid/requests/compute/grid_loadbalancer_list.rb
    lib/brightbox-fog/go_grid/requests/compute/grid_server_add.rb
    lib/brightbox-fog/go_grid/requests/compute/grid_server_delete.rb
    lib/brightbox-fog/go_grid/requests/compute/grid_server_get.rb
    lib/brightbox-fog/go_grid/requests/compute/grid_server_list.rb
    lib/brightbox-fog/go_grid/requests/compute/grid_server_power.rb
    lib/brightbox-fog/google.rb
    lib/brightbox-fog/google/bin.rb
    lib/brightbox-fog/google/models/storage/directories.rb
    lib/brightbox-fog/google/models/storage/directory.rb
    lib/brightbox-fog/google/models/storage/file.rb
    lib/brightbox-fog/google/models/storage/files.rb
    lib/brightbox-fog/google/parsers/storage/access_control_list.rb
    lib/brightbox-fog/google/parsers/storage/copy_object.rb
    lib/brightbox-fog/google/parsers/storage/get_bucket.rb
    lib/brightbox-fog/google/parsers/storage/get_bucket_logging.rb
    lib/brightbox-fog/google/parsers/storage/get_bucket_object_versions.rb
    lib/brightbox-fog/google/parsers/storage/get_bucket_versioning.rb
    lib/brightbox-fog/google/parsers/storage/get_request_payment.rb
    lib/brightbox-fog/google/parsers/storage/get_service.rb
    lib/brightbox-fog/google/requests/storage/copy_object.rb
    lib/brightbox-fog/google/requests/storage/delete_bucket.rb
    lib/brightbox-fog/google/requests/storage/delete_object.rb
    lib/brightbox-fog/google/requests/storage/get_bucket.rb
    lib/brightbox-fog/google/requests/storage/get_bucket_acl.rb
    lib/brightbox-fog/google/requests/storage/get_object.rb
    lib/brightbox-fog/google/requests/storage/get_object_acl.rb
    lib/brightbox-fog/google/requests/storage/get_object_torrent.rb
    lib/brightbox-fog/google/requests/storage/get_object_url.rb
    lib/brightbox-fog/google/requests/storage/get_service.rb
    lib/brightbox-fog/google/requests/storage/head_object.rb
    lib/brightbox-fog/google/requests/storage/put_bucket.rb
    lib/brightbox-fog/google/requests/storage/put_bucket_acl.rb
    lib/brightbox-fog/google/requests/storage/put_object.rb
    lib/brightbox-fog/google/requests/storage/put_object_url.rb
    lib/brightbox-fog/google/storage.rb
    lib/brightbox-fog/linode.rb
    lib/brightbox-fog/linode/bin.rb
    lib/brightbox-fog/linode/compute.rb
    lib/brightbox-fog/linode/requests/compute/avail_datacenters.rb
    lib/brightbox-fog/linode/requests/compute/avail_distributions.rb
    lib/brightbox-fog/linode/requests/compute/avail_kernels.rb
    lib/brightbox-fog/linode/requests/compute/avail_linodeplans.rb
    lib/brightbox-fog/linode/requests/compute/avail_stackscripts.rb
    lib/brightbox-fog/linode/requests/compute/linode_create.rb
    lib/brightbox-fog/linode/requests/compute/linode_delete.rb
    lib/brightbox-fog/linode/requests/compute/linode_list.rb
    lib/brightbox-fog/linode/requests/compute/linode_reboot.rb
    lib/brightbox-fog/local.rb
    lib/brightbox-fog/local/bin.rb
    lib/brightbox-fog/local/models/storage/directories.rb
    lib/brightbox-fog/local/models/storage/directory.rb
    lib/brightbox-fog/local/models/storage/file.rb
    lib/brightbox-fog/local/models/storage/files.rb
    lib/brightbox-fog/local/storage.rb
    lib/brightbox-fog/new_servers.rb
    lib/brightbox-fog/new_servers/bin.rb
    lib/brightbox-fog/new_servers/compute.rb
    lib/brightbox-fog/new_servers/requests/compute/add_server.rb
    lib/brightbox-fog/new_servers/requests/compute/cancel_server.rb
    lib/brightbox-fog/new_servers/requests/compute/get_server.rb
    lib/brightbox-fog/new_servers/requests/compute/list_images.rb
    lib/brightbox-fog/new_servers/requests/compute/list_plans.rb
    lib/brightbox-fog/new_servers/requests/compute/list_servers.rb
    lib/brightbox-fog/new_servers/requests/compute/reboot_server.rb
    lib/brightbox-fog/rackspace.rb
    lib/brightbox-fog/rackspace/bin.rb
    lib/brightbox-fog/rackspace/cdn.rb
    lib/brightbox-fog/rackspace/compute.rb
    lib/brightbox-fog/rackspace/files.rb
    lib/brightbox-fog/rackspace/models/compute/flavor.rb
    lib/brightbox-fog/rackspace/models/compute/flavors.rb
    lib/brightbox-fog/rackspace/models/compute/image.rb
    lib/brightbox-fog/rackspace/models/compute/images.rb
    lib/brightbox-fog/rackspace/models/compute/server.rb
    lib/brightbox-fog/rackspace/models/compute/servers.rb
    lib/brightbox-fog/rackspace/models/storage/directories.rb
    lib/brightbox-fog/rackspace/models/storage/directory.rb
    lib/brightbox-fog/rackspace/models/storage/file.rb
    lib/brightbox-fog/rackspace/models/storage/files.rb
    lib/brightbox-fog/rackspace/requests/cdn/get_cdn_containers.rb
    lib/brightbox-fog/rackspace/requests/cdn/head_cdn_container.rb
    lib/brightbox-fog/rackspace/requests/cdn/put_cdn_container.rb
    lib/brightbox-fog/rackspace/requests/compute/create_image.rb
    lib/brightbox-fog/rackspace/requests/compute/create_server.rb
    lib/brightbox-fog/rackspace/requests/compute/delete_image.rb
    lib/brightbox-fog/rackspace/requests/compute/delete_server.rb
    lib/brightbox-fog/rackspace/requests/compute/get_flavor_details.rb
    lib/brightbox-fog/rackspace/requests/compute/get_image_details.rb
    lib/brightbox-fog/rackspace/requests/compute/get_server_details.rb
    lib/brightbox-fog/rackspace/requests/compute/list_addresses.rb
    lib/brightbox-fog/rackspace/requests/compute/list_flavors.rb
    lib/brightbox-fog/rackspace/requests/compute/list_flavors_detail.rb
    lib/brightbox-fog/rackspace/requests/compute/list_images.rb
    lib/brightbox-fog/rackspace/requests/compute/list_images_detail.rb
    lib/brightbox-fog/rackspace/requests/compute/list_private_addresses.rb
    lib/brightbox-fog/rackspace/requests/compute/list_public_addresses.rb
    lib/brightbox-fog/rackspace/requests/compute/list_servers.rb
    lib/brightbox-fog/rackspace/requests/compute/list_servers_detail.rb
    lib/brightbox-fog/rackspace/requests/compute/reboot_server.rb
    lib/brightbox-fog/rackspace/requests/compute/update_server.rb
    lib/brightbox-fog/rackspace/requests/storage/delete_container.rb
    lib/brightbox-fog/rackspace/requests/storage/delete_object.rb
    lib/brightbox-fog/rackspace/requests/storage/get_container.rb
    lib/brightbox-fog/rackspace/requests/storage/get_containers.rb
    lib/brightbox-fog/rackspace/requests/storage/get_object.rb
    lib/brightbox-fog/rackspace/requests/storage/head_container.rb
    lib/brightbox-fog/rackspace/requests/storage/head_containers.rb
    lib/brightbox-fog/rackspace/requests/storage/head_object.rb
    lib/brightbox-fog/rackspace/requests/storage/put_container.rb
    lib/brightbox-fog/rackspace/requests/storage/put_object.rb
    lib/brightbox-fog/rackspace/servers.rb
    lib/brightbox-fog/rackspace/storage.rb
    lib/brightbox-fog/slicehost.rb
    lib/brightbox-fog/slicehost/bin.rb
    lib/brightbox-fog/slicehost/compute.rb
    lib/brightbox-fog/slicehost/models/compute/flavor.rb
    lib/brightbox-fog/slicehost/models/compute/flavors.rb
    lib/brightbox-fog/slicehost/models/compute/image.rb
    lib/brightbox-fog/slicehost/models/compute/images.rb
    lib/brightbox-fog/slicehost/models/compute/server.rb
    lib/brightbox-fog/slicehost/models/compute/servers.rb
    lib/brightbox-fog/slicehost/parsers/compute/create_slice.rb
    lib/brightbox-fog/slicehost/parsers/compute/get_backups.rb
    lib/brightbox-fog/slicehost/parsers/compute/get_flavor.rb
    lib/brightbox-fog/slicehost/parsers/compute/get_flavors.rb
    lib/brightbox-fog/slicehost/parsers/compute/get_image.rb
    lib/brightbox-fog/slicehost/parsers/compute/get_images.rb
    lib/brightbox-fog/slicehost/parsers/compute/get_slice.rb
    lib/brightbox-fog/slicehost/parsers/compute/get_slices.rb
    lib/brightbox-fog/slicehost/requests/compute/create_slice.rb
    lib/brightbox-fog/slicehost/requests/compute/delete_slice.rb
    lib/brightbox-fog/slicehost/requests/compute/get_backups.rb
    lib/brightbox-fog/slicehost/requests/compute/get_flavor.rb
    lib/brightbox-fog/slicehost/requests/compute/get_flavors.rb
    lib/brightbox-fog/slicehost/requests/compute/get_image.rb
    lib/brightbox-fog/slicehost/requests/compute/get_images.rb
    lib/brightbox-fog/slicehost/requests/compute/get_slice.rb
    lib/brightbox-fog/slicehost/requests/compute/get_slices.rb
    lib/brightbox-fog/slicehost/requests/compute/reboot_slice.rb
    lib/brightbox-fog/terremark.rb
    lib/brightbox-fog/terremark/bin.rb
    lib/brightbox-fog/terremark/ecloud.rb
    lib/brightbox-fog/terremark/models/shared/address.rb
    lib/brightbox-fog/terremark/models/shared/addresses.rb
    lib/brightbox-fog/terremark/models/shared/network.rb
    lib/brightbox-fog/terremark/models/shared/networks.rb
    lib/brightbox-fog/terremark/models/shared/server.rb
    lib/brightbox-fog/terremark/models/shared/servers.rb
    lib/brightbox-fog/terremark/models/shared/task.rb
    lib/brightbox-fog/terremark/models/shared/tasks.rb
    lib/brightbox-fog/terremark/models/shared/vdc.rb
    lib/brightbox-fog/terremark/models/shared/vdcs.rb
    lib/brightbox-fog/terremark/parser.rb
    lib/brightbox-fog/terremark/parsers/shared/get_catalog.rb
    lib/brightbox-fog/terremark/parsers/shared/get_catalog_item.rb
    lib/brightbox-fog/terremark/parsers/shared/get_internet_services.rb
    lib/brightbox-fog/terremark/parsers/shared/get_network_ips.rb
    lib/brightbox-fog/terremark/parsers/shared/get_node_services.rb
    lib/brightbox-fog/terremark/parsers/shared/get_organization.rb
    lib/brightbox-fog/terremark/parsers/shared/get_organizations.rb
    lib/brightbox-fog/terremark/parsers/shared/get_public_ips.rb
    lib/brightbox-fog/terremark/parsers/shared/get_tasks_list.rb
    lib/brightbox-fog/terremark/parsers/shared/get_vapp_template.rb
    lib/brightbox-fog/terremark/parsers/shared/get_vdc.rb
    lib/brightbox-fog/terremark/parsers/shared/instantiate_vapp_template.rb
    lib/brightbox-fog/terremark/parsers/shared/internet_service.rb
    lib/brightbox-fog/terremark/parsers/shared/network.rb
    lib/brightbox-fog/terremark/parsers/shared/node_service.rb
    lib/brightbox-fog/terremark/parsers/shared/public_ip.rb
    lib/brightbox-fog/terremark/parsers/shared/task.rb
    lib/brightbox-fog/terremark/parsers/shared/vapp.rb
    lib/brightbox-fog/terremark/requests/shared/add_internet_service.rb
    lib/brightbox-fog/terremark/requests/shared/add_node_service.rb
    lib/brightbox-fog/terremark/requests/shared/create_internet_service.rb
    lib/brightbox-fog/terremark/requests/shared/delete_internet_service.rb
    lib/brightbox-fog/terremark/requests/shared/delete_node_service.rb
    lib/brightbox-fog/terremark/requests/shared/delete_public_ip.rb
    lib/brightbox-fog/terremark/requests/shared/delete_vapp.rb
    lib/brightbox-fog/terremark/requests/shared/deploy_vapp.rb
    lib/brightbox-fog/terremark/requests/shared/get_catalog.rb
    lib/brightbox-fog/terremark/requests/shared/get_catalog_item.rb
    lib/brightbox-fog/terremark/requests/shared/get_internet_services.rb
    lib/brightbox-fog/terremark/requests/shared/get_network.rb
    lib/brightbox-fog/terremark/requests/shared/get_network_ips.rb
    lib/brightbox-fog/terremark/requests/shared/get_node_services.rb
    lib/brightbox-fog/terremark/requests/shared/get_organization.rb
    lib/brightbox-fog/terremark/requests/shared/get_organizations.rb
    lib/brightbox-fog/terremark/requests/shared/get_public_ip.rb
    lib/brightbox-fog/terremark/requests/shared/get_public_ips.rb
    lib/brightbox-fog/terremark/requests/shared/get_task.rb
    lib/brightbox-fog/terremark/requests/shared/get_tasks_list.rb
    lib/brightbox-fog/terremark/requests/shared/get_vapp.rb
    lib/brightbox-fog/terremark/requests/shared/get_vapp_template.rb
    lib/brightbox-fog/terremark/requests/shared/get_vdc.rb
    lib/brightbox-fog/terremark/requests/shared/instantiate_vapp_template.rb
    lib/brightbox-fog/terremark/requests/shared/power_off.rb
    lib/brightbox-fog/terremark/requests/shared/power_on.rb
    lib/brightbox-fog/terremark/requests/shared/power_reset.rb
    lib/brightbox-fog/terremark/requests/shared/power_shutdown.rb
    lib/brightbox-fog/terremark/shared.rb
    lib/brightbox-fog/terremark/vcloud.rb
    lib/brightbox-fog/vcloud.rb
    lib/brightbox-fog/vcloud/bin.rb
    lib/brightbox-fog/vcloud/collection.rb
    lib/brightbox-fog/vcloud/generators.rb
    lib/brightbox-fog/vcloud/model.rb
    lib/brightbox-fog/vcloud/models/vdc.rb
    lib/brightbox-fog/vcloud/models/vdcs.rb
    lib/brightbox-fog/vcloud/requests/get_network.rb
    lib/brightbox-fog/vcloud/requests/get_organization.rb
    lib/brightbox-fog/vcloud/requests/get_vdc.rb
    lib/brightbox-fog/vcloud/requests/get_versions.rb
    lib/brightbox-fog/vcloud/requests/login.rb
    lib/brightbox-fog/vcloud/terremark/ecloud.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/catalog.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/catalog_item.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/firewall_acl.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/firewall_acls.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/internet_service.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/internet_services.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/ip.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/ips.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/network.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/networks.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/node.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/nodes.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/public_ip.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/public_ips.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/server.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/servers.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/task.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/tasks.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/vdc.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/models/vdcs.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/add_internet_service.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/add_node.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/clone_vapp.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/configure_internet_service.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/configure_network.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/configure_network_ip.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/configure_node.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/configure_vapp.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/delete_internet_service.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/delete_node.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/delete_vapp.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_catalog.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_catalog_item.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_customization_options.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_firewall_acl.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_firewall_acls.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_internet_services.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_network.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_network_extensions.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_network_ip.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_network_ips.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_node.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_nodes.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_public_ip.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_public_ips.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_task.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_task_list.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_vapp.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_vapp_template.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/get_vdc.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/instantiate_vapp_template.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/power_off.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/power_on.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/power_reset.rb
    lib/brightbox-fog/vcloud/terremark/ecloud/requests/power_shutdown.rb
    lib/brightbox-fog/vcloud/terremark/vcloud.rb
    lib/brightbox-fog/vcloud/terremark/vcloud/requests/get_vdc.rb
    spec/aws/models/compute/address_spec.rb
    spec/aws/models/compute/addresses_spec.rb
    spec/aws/models/compute/flavors_spec.rb
    spec/aws/models/compute/key_pair_spec.rb
    spec/aws/models/compute/key_pairs_spec.rb
    spec/aws/models/compute/security_group_spec.rb
    spec/aws/models/compute/security_groups_spec.rb
    spec/aws/models/compute/server_spec.rb
    spec/aws/models/compute/servers_spec.rb
    spec/aws/models/compute/snapshot_spec.rb
    spec/aws/models/compute/snapshots_spec.rb
    spec/aws/models/compute/volume_spec.rb
    spec/aws/models/compute/volumes_spec.rb
    spec/aws/requests/simpledb/batch_put_attributes_spec.rb
    spec/aws/requests/simpledb/create_domain_spec.rb
    spec/aws/requests/simpledb/delete_attributes_spec.rb
    spec/aws/requests/simpledb/delete_domain_spec.rb
    spec/aws/requests/simpledb/domain_metadata_spec.rb
    spec/aws/requests/simpledb/get_attributes_spec.rb
    spec/aws/requests/simpledb/list_domains_spec.rb
    spec/aws/requests/simpledb/put_attributes_spec.rb
    spec/aws/requests/simpledb/select_spec.rb
    spec/bluebox/models/compute/flavors_spec.rb
    spec/bluebox/models/compute/server_spec.rb
    spec/bluebox/models/compute/servers_spec.rb
    spec/brightbox/models/flavors_spec.rb
    spec/brightbox/models/server_spec.rb
    spec/brightbox/models/servers_spec.rb
    spec/compact_progress_bar_formatter.rb
    spec/google/requests/storage/copy_object_spec.rb
    spec/google/requests/storage/delete_bucket_spec.rb
    spec/google/requests/storage/delete_object_spec.rb
    spec/google/requests/storage/get_bucket_spec.rb
    spec/google/requests/storage/get_object_spec.rb
    spec/google/requests/storage/get_service_spec.rb
    spec/google/requests/storage/head_object_spec.rb
    spec/google/requests/storage/put_bucket_spec.rb
    spec/google/requests/storage/put_object_spec.rb
    spec/lorem.txt
    spec/rackspace/models/compute/flavors_spec.rb
    spec/rackspace/models/compute/server_spec.rb
    spec/rackspace/models/compute/servers_spec.rb
    spec/shared_examples/flavors_examples.rb
    spec/shared_examples/server_examples.rb
    spec/shared_examples/servers_examples.rb
    spec/slicehost/models/compute/flavors_spec.rb
    spec/slicehost/models/compute/server_spec.rb
    spec/slicehost/models/compute/servers_spec.rb
    spec/spec_helper.rb
    spec/vcloud/bin_spec.rb
    spec/vcloud/models/vdc_spec.rb
    spec/vcloud/models/vdcs_spec.rb
    spec/vcloud/requests/get_network_spec.rb
    spec/vcloud/requests/get_organization_spec.rb
    spec/vcloud/requests/get_vdc_spec.rb
    spec/vcloud/requests/get_versions_spec.rb
    spec/vcloud/requests/login_spec.rb
    spec/vcloud/spec_helper.rb
    spec/vcloud/terremark/ecloud/models/internet_service_spec.rb
    spec/vcloud/terremark/ecloud/models/internet_services_spec.rb
    spec/vcloud/terremark/ecloud/models/ip_spec.rb
    spec/vcloud/terremark/ecloud/models/ips_spec.rb
    spec/vcloud/terremark/ecloud/models/network_spec.rb
    spec/vcloud/terremark/ecloud/models/networks_spec.rb
    spec/vcloud/terremark/ecloud/models/node_spec.rb
    spec/vcloud/terremark/ecloud/models/nodes_spec.rb
    spec/vcloud/terremark/ecloud/models/public_ip_spec.rb
    spec/vcloud/terremark/ecloud/models/public_ips_spec.rb
    spec/vcloud/terremark/ecloud/models/vdc_spec.rb
    spec/vcloud/terremark/ecloud/models/vdcs_spec.rb
    spec/vcloud/terremark/ecloud/requests/add_internet_service_spec.rb
    spec/vcloud/terremark/ecloud/requests/add_node_spec.rb
    spec/vcloud/terremark/ecloud/requests/configure_internet_service_spec.rb
    spec/vcloud/terremark/ecloud/requests/configure_node_spec.rb
    spec/vcloud/terremark/ecloud/requests/delete_internet_service_spec.rb
    spec/vcloud/terremark/ecloud/requests/delete_node_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_catalog_item_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_catalog_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_customization_options_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_internet_services_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_network_ip_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_network_ips_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_network_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_node_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_nodes_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_public_ip_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_public_ips_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_vapp_spec.rb
    spec/vcloud/terremark/ecloud/requests/get_vdc_spec.rb
    spec/vcloud/terremark/ecloud/requests/instantiate_vapp_template_spec.rb
    spec/vcloud/terremark/ecloud/requests/login_spec.rb
    spec/vcloud/terremark/ecloud/requests/power_on_spec.rb
    spec/vcloud/vcloud_spec.rb
    tests/aws/helper.rb
    tests/aws/models/storage/directories_tests.rb
    tests/aws/models/storage/directory_tests.rb
    tests/aws/models/storage/file_tests.rb
    tests/aws/models/storage/files_tests.rb
    tests/aws/requests/compute/address_tests.rb
    tests/aws/requests/compute/availability_zone_tests.rb
    tests/aws/requests/compute/image_tests.rb
    tests/aws/requests/compute/instance_tests.rb
    tests/aws/requests/compute/key_pair_tests.rb
    tests/aws/requests/compute/region_tests.rb
    tests/aws/requests/compute/security_group_tests.rb
    tests/aws/requests/compute/snapshot_tests.rb
    tests/aws/requests/compute/tag_tests.rb
    tests/aws/requests/compute/volume_tests.rb
    tests/aws/requests/storage/bucket_tests.rb
    tests/aws/requests/storage/object_tests.rb
    tests/bluebox/helper.rb
    tests/bluebox/requests/compute/block_tests.rb
    tests/bluebox/requests/compute/product_tests.rb
    tests/bluebox/requests/compute/template_tests.rb
    tests/go_grid/helper.rb
    tests/go_grid/requests/compute/image_tests.rb
    tests/google/models/storage/directories_tests.rb
    tests/google/models/storage/directory_tests.rb
    tests/google/models/storage/file_tests.rb
    tests/google/models/storage/files_tests.rb
    tests/helper.rb
    tests/helper_tests.rb
    tests/helpers/storage/directories_tests.rb
    tests/helpers/storage/directory_tests.rb
    tests/helpers/storage/file_tests.rb
    tests/helpers/storage/files_tests.rb
    tests/linode/helper.rb
    tests/linode/requests/compute/datacenter_tests.rb
    tests/linode/requests/compute/distribution_tests.rb
    tests/linode/requests/compute/linode_tests.rb
    tests/linode/requests/compute/linodeplans_tests.rb
    tests/local/models/storage/directories_tests.rb
    tests/local/models/storage/directory_tests.rb
    tests/local/models/storage/file_tests.rb
    tests/local/models/storage/files_tests.rb
    tests/lorem.txt
    tests/rackspace/helper.rb
    tests/rackspace/models/storage/directories_tests.rb
    tests/rackspace/models/storage/directory_tests.rb
    tests/rackspace/models/storage/file_tests.rb
    tests/rackspace/models/storage/files_tests.rb
    tests/rackspace/requests/compute/address_tests.rb
    tests/rackspace/requests/compute/flavor_tests.rb
    tests/rackspace/requests/compute/image_tests.rb
    tests/rackspace/requests/compute/server_tests.rb
    tests/rackspace/requests/storage/container_tests.rb
    tests/rackspace/requests/storage/object_tests.rb
    tests/slicehost/helper.rb
    tests/slicehost/requests/compute/backup_tests.rb
    tests/slicehost/requests/compute/flavor_tests.rb
    tests/slicehost/requests/compute/image_tests.rb
    tests/slicehost/requests/compute/slice_tests.rb
  ]
  # = MANIFEST =

  ## Test files will be grabbed from the file list. Make sure the path glob
  ## matches what you actually use.
  s.test_files = s.files.select { |path| path =~ /^[spec|tests]\/.*_[spec|tests]\.rb/ }
end
